export const NAME_EPICS = {
    EPIC_UTILITYBILL_SCREEN: {
        EPIC_UTILITYBILL_SCREEN:'EPIC_UTILITYBILL_SCREEN',
        
        EPIC_GET_UTILITYBILL:'EPIC_GET_UTILITYBILL',
        EPIC_GET_UTILITYBILL_FAILED:'EPIC_GET_UTILITYBILL_FAILED',

        EPIC_EDIT_UTILITYBILL:'EPIC_EDIT_UTILITYBILL',
        EPIC_EDIT_UTILITYBILL_FAILED:'EPIC_EDIT_UTILITYBILL_FAILED',

        EPIC_CREATE_UTILITYBILL:'EPIC_CREATE_UTILITYBILL',
        EPIC_CREATE_UTILITYBILL_FAILED:'EPIC_CREATE_UTILITYBILL_FAILED',

        EPIC_DELETE_UTILITYBILL:'EPIC_DELETE_UTILITYBILL',
        EPIC_DELETE_UTILITYBILL_FAILED:'EPIC_DELETE_UTILITYBILL_FAILED',
        
    },
}