export const NAME_EPICS = {
    EPIC_HOUSE_SCREEN: {
        EPIC_HOUSE_SCREEN:'EPIC_HOUSE_SCREEN',
        EPIC_GET_HOUSE:'EPIC_GET_HOUSE',
        EPIC_GET_HOUSE_FAILED:'EPIC_GET_HOUSE_FAILED',

        EPIC_EDIT_HOUSE:'EPIC_EDIT_HOUSE',
        EPIC_EDIT_HOUSE_FAILED:'EPIC_EDIT_HOUSE_FAILED',

        EPIC_CREATE_HOUSE:'EPIC_CREATE_HOUSE',
        EPIC_CREATE_HOUSE_FAILED:'EPIC_CREATE_HOUSE_FAILED',

        EPIC_DELETE_HOUSE:'EPIC_DELETE_HOUSE',
        EPIC_DELETE_HOUSE_FAILED:'EPIC_DELETE_HOUSE_FAILED',
        
    },
}