export const NAME_ACTIONS = {
  UTILITYBILL_SCREEN: {
    UTILITYBILL_SCREEN: 'UTILITYBILL_SCREEN',
    GET_UTILITYBILL: 'GET_UTILITYBILL',
    GET_UTILITYBILL_FAILED: 'GET_UTILITYBILL_FAILED',

    CREATE_UTILITYBILL:'CREATE_UTILITYBILL',
    CREATE_UTILITYBILL_FAILED:'CREATE_UTILITYBILL_FAILED',
    
    EDIT_UTILITYBILL:'EDIT_UTILITYBILL',
    EDIT_UTILITYBILL_FAILED:'EDIT_UTILITYBILL_FAILED',

    DELETE_UTILITYBILL:'DELETE_UTILITYBILL',
    DELETE_UTILITYBILL_FAILED:'DELETE_UTILITYBILL_FAILED',
  }
};
