export const NAME_EPICS = {
    EPIC_STATISTICAL_SCREEN: {
        EPIC_STATISTICAL_SCREEN:'EPIC_STATISTICAL_SCREEN',
        EPIC_GET_STATISTICAL:'EPIC_GET_STATISTICAL',
        EPIC_GET_STATISTICAL_FAILED:'EPIC_GET_STATISTICAL_FAILED',

    },
}