export const NAME_ACTIONS = {
  CONTRACT_SCREEN: {

    CONTRACT_SCREEN: 'CONTRACT_SCREEN',
    
    GET_CONTRACT: 'GET_CONTRACT',
    GET_CONTRACT_FAILED: 'GET_CONTRACT_FAILED',

    CREATE_CONTRACT:'CREATE_CONTRACT',
    CREATE_CONTRACT_FAILED:'CREATE_CONTRACT_FAILED',
    
    EDIT_CONTRACT:'EDIT_CONTRACT',
    EDIT_CONTRACT_FAILED:'EDIT_CONTRACT_FAILED',

    DELETE_CONTRACT:'DELETE_CONTRACT',
    DELETE_CONTRACT_FAILED:'DELETE_CONTRACT_FAILED',
  }
};
