export const NAME_EPICS = {
    EPIC_USER_SCREEN: {
        EPIC_USER_SCREEN:'EPIC_USER_SCREEN',
        EPIC_GET_USER:'EPIC_GET_USER',
        EPIC_GET_USER_FAILED:'EPIC_GET_USER_FAILED',

        EPIC_EDIT_USER:'EPIC_EDIT_USER',
        EPIC_EDIT_USER_FAILED:'EPIC_EDIT_USER_FAILED',

        EPIC_CHANGE_PASSWORD:'EPIC_CHANGE_PASSWORD',
        EPIC_CHANGE_PASSWORD_FAILED:'EPIC_CHANGE_PASSWORD_FAILED',
        
    },
}