export const NAME_EPICS = {
    EPIC_CUSTOMER_SCREEN: {
        EPIC_CUSTOMER_SCREEN:'EPIC_CUSTOMER_SCREEN',
        EPIC_GET_CUSTOMER:'EPIC_GET_CUSTOMER',
        EPIC_GET_CUSTOMER_FAILED:'EPIC_GET_CUSTOMER_FAILED',

        EPIC_EDIT_CUSTOMER:'EPIC_EDIT_CUSTOMER',
        EPIC_EDIT_CUSTOMER_FAILED:'EPIC_EDIT_CUSTOMER_FAILED',

        EPIC_CREATE_CUSTOMER:'EPIC_CREATE_CUSTOMER',
        EPIC_CREATE_CUSTOMER_FAILED:'EPIC_CREATE_CUSTOMER_FAILED',

        EPIC_DELETE_CUSTOMER:'EPIC_DELETE_CUSTOMER',
        EPIC_DELETE_CUSTOMER_FAILED:'EPIC_DELETE_CUSTOMER_FAILED',
        
    },
}