export const NAME_ACTIONS = {
  USER_SCREEN: {
    USER_SCREEN: 'USER_SCREEN',
    GET_USER: 'GET_USER',
    GET_USER_FAILED: 'GET_USER_FAILED',

    CHANGE_PASSWORD:'CHANGE_PASSWORD',
    CHANGE_PASSWORD_FAILED:'CHANGE_PASSWORD_FAILED',
    
    EDIT_USER:'EDIT_USER',
    EDIT_USER_FAILED:'EDIT_USER_FAILED',

  }
};
