export const NAME_EPICS = {
    EPIC_BILL_SCREEN: {
        EPIC_BILL_SCREEN:'EPIC_BILL_SCREEN',
        EPIC_GET_BILL:'EPIC_GET_BILL',
        EPIC_GET_BILL_FAILED:'EPIC_GET_BILL_FAILED',

        EPIC_EDIT_BILL:'EPIC_EDIT_BILL',
        EPIC_EDIT_BILL_FAILED:'EPIC_EDIT_BILL_FAILED',

        EPIC_CREATE_BILL:'EPIC_CREATE_BILL',
        EPIC_CREATE_BILL_FAILED:'EPIC_CREATE_BILL_FAILED',

        EPIC_DELETE_BILL:'EPIC_DELETE_BILL',
        EPIC_DELETE_BILL_FAILED:'EPIC_DELETE_BILL_FAILED',
        
    },
}