export const NAME_ACTIONS = {
  STATISTICAL_SCREEN: {
    STATISTICAL_SCREEN: 'STATISTICAL_SCREEN',
    GET_STATISTICAL: 'GET_STATISTICAL',
    GET_STATISTICAL_FAILED: 'GET_STATISTICAL_FAILED',
  }
};
