export const NAME_EPICS = {
    EPIC_CONTRACT_SCREEN: {
        EPIC_CONTRACT_SCREEN:'EPIC_CONTRACT_SCREEN',
        EPIC_GET_CONTRACT:'EPIC_GET_CONTRACT',
        EPIC_GET_CONTRACT_FAILED:'EPIC_GET_CONTRACT_FAILED',

        EPIC_EDIT_CONTRACT:'EPIC_EDIT_CONTRACT',
        EPIC_EDIT_CONTRACT_FAILED:'EPIC_EDIT_CONTRACT_FAILED',

        EPIC_CREATE_CONTRACT:'EPIC_CREATE_CONTRACT',
        EPIC_CREATE_CONTRACT_FAILED:'EPIC_CREATE_CONTRACT_FAILED',

        EPIC_DELETE_CONTRACT:'EPIC_DELETE_CONTRACT',
        EPIC_DELETE_CONTRACT_FAILED:'EPIC_DELETE_CONTRACT_FAILED',
        
    },
}