export const NAME_ACTIONS = {
  DICHVU_SCREEN: {

    DICHVU_SCREEN: 'DICHVU_SCREEN',
    
    GET_DICHVU: 'GET_DICHVU',
    GET_DICHVU_FAILED: 'GET_DICHVU_FAILED',

    CREATE_DICHVU:'CREATE_DICHVU',
    CREATE_DICHVU_FAILED:'CREATE_DICHVU_FAILED',
    
    EDIT_DICHVU:'EDIT_DICHVU',
    EDIT_DICHVU_FAILED:'EDIT_DICHVU_FAILED',

    DELETE_DICHVU:'DELETE_DICHVU',
    DELETE_DICHVU_FAILED:'DELETE_DICHVU_FAILED',
  }
};
