export const NAME_EPICS = {
    EPIC_ROOM_SCREEN: {
        EPIC_ROOM_SCREEN:'EPIC_ROOM_SCREEN',
        EPIC_GET_ROOM:'EPIC_GET_ROOM',
        EPIC_GET_ROOM_FAILED:'EPIC_GET_ROOM_FAILED',

        EPIC_EDIT_ROOM:'EPIC_EDIT_ROOM',
        EPIC_EDIT_ROOM_FAILED:'EPIC_EDIT_ROOM_FAILED',

        EPIC_CREATE_ROOM:'EPIC_CREATE_ROOM',
        EPIC_CREATE_ROOM_FAILED:'EPIC_CREATE_ROOM_FAILED',

        EPIC_DELETE_ROOM:'EPIC_DELETE_ROOM',
        EPIC_DELETE_ROOM_FAILED:'EPIC_DELETE_ROOM_FAILED',
        //
        EPIC_ADD_PERSON_TO_ROOM:'EPIC_ADD_PERSON_TO_ROOM',
        EPIC_ADD_PERSON_TO_ROOM_FAILED:'EPIC_ADD_PERSON_TO_ROOM_FAILED',

        EPIC_REMOVE_PERSON_TO_ROOM:'EPIC_REMOVE_PERSON_TO_ROOM',
        EPIC_REMOVE_PERSON_TO_ROOM_FAILED:'EPIC_REMOVE_PERSON_TO_ROOM_FAILED',

        EPIC_ADD_SERVICE_TO_ROOM:'EPIC_ADD_SERVICE_TO_ROOM',
        EPIC_ADD_SERVICE_TO_ROOM_FAILED:'EPIC_ADD_SERVICE_TO_ROOM_FAILED',

        EPIC_REMOVE_SERVICE_TO_ROOM:'EPIC_REMOVE_SERVICE_TO_ROOM',
        EPIC_REMOVE_SERVICE_TO_ROOM_FAILED:'EPIC_REMOVE_SERVICE_TO_ROOM_FAILED',
        
        EPIC_GET_EMPTY_ROOM:'EPIC_GET_EMPTY_ROOM',
        EPIC_GET_EMPTY_ROOM_FAILED:'EPIC_GET_EMPTY_ROOM_FAILED',

        EPIC_GET_NOT_EMPTY_ROOM:'EPIC_GET_NOT_EMPTY_ROOM',
        EPIC_GET_NOT_EMPTY_ROOM_FAILED:'EPIC_GET_NOT_EMPTY_ROOM_FAILED',

        EPIC_GET_PERSON_TO_ROOM:'EPIC_GET_PERSON_TO_ROOM',
        EPIC_GET_PERSON_TO_ROOM_FAILED:'EPIC_GET_PERSON_TO_ROOM_FAILED',
        
        EPIC_GET_SERVICE_TO_ROOM:'EPIC_GET_SERVICE_TO_ROOM',
        EPIC_GET_SERVICE_TO_ROOM_FAILED:'EPIC_GET_SERVICE_TO_ROOM_FAILED',
        

    },
}