export const NAME_ACTIONS = {
  BILL_SCREEN: {
    BILL_SCREEN: 'BILL_SCREEN',
    GET_BILL: 'GET_BILL',
    GET_BILL_FAILED: 'GET_BILL_FAILED',

    CREATE_BILL:'CREATE_BILL',
    CREATE_BILL_FAILED:'CREATE_BILL_FAILED',
    
    EDIT_BILL:'EDIT_BILL',
    EDIT_BILL_FAILED:'EDIT_BILL_FAILED',

    RECALCULATE_BILL:'RECALCULATE_BILL',
    RECALCULATE_BILL_FAILED:'RECALCULATE_BILL_FAILED',

    DELETE_BILL:'DELETE_BILL',
    DELETE_BILL_FAILED:'DELETE_BILL_FAILED',
  }
};
