export const NAME_ACTIONS = {
  CUSTOMER_SCREEN: {
    CUSTOMER_SCREEN: 'CUSTOMER_SCREEN',
    GET_CUSTOMER: 'GET_CUSTOMER',
    GET_CUSTOMER_FAILED: 'GET_CUSTOMER_FAILED',

    CREATE_CUSTOMER:'CREATE_CUSTOMER',
    CREATE_CUSTOMER_FAILED:'CREATE_CUSTOMER_FAILED',
    
    EDIT_CUSTOMER:'EDIT_CUSTOMER',
    EDIT_CUSTOMER_FAILED:'EDIT_CUSTOMER_FAILED',

    DELETE_CUSTOMER:'DELETE_CUSTOMER',
    DELETE_CUSTOMER_FAILED:'DELETE_CUSTOMER_FAILED',
  }
};
