export const NAME_ACTIONS = {
  ROOM_SCREEN: {
    ROOM_SCREEN: 'ROOM_SCREEN',
    GET_ROOM: 'GET_ROOM',
    GET_ROOM_FAILED: 'GET_ROOM_FAILED',

    CREATE_ROOM:'CREATE_ROOM',
    CREATE_ROOM_FAILED:'CREATE_ROOM_FAILED',
    
    EDIT_ROOM:'EDIT_ROOM',
    EDIT_ROOM_FAILED:'EDIT_ROOM_FAILED',

    DELETE_ROOM:'DELETE_ROOM',
    DELETE_ROOM_FAILED:'DELETE_ROOM_FAILED',

    ADD_PERSON_TO_ROOM:'ADD_PERSON_TO_ROOM',
    ADD_PERSON_TO_ROOM_FAILED:'ADD_PERSON_TO_ROOM_FAILED',

    REMOVE_PERSON_TO_ROOM:'REMOVE_PERSON_TO_ROOM',
    REMOVE_PERSON_TO_ROOM_FAILED:'REMOVE_PERSON_TO_ROOM_FAILED',

    ADD_SERVICE_TO_ROOM:'ADD_SERVICE_TO_ROOM',
    ADD_SERVICE_TO_ROOM_FAILED:'ADD_SERVICE_TO_ROOM_FAILED',

    REMOVE_SERVICE_TO_ROOM:'REMOVE_SERVICE_TO_ROOM',
    REMOVE_SERVICE_TO_ROOM_FAILED:'REMOVE_SERVICE_TO_ROOM_FAILED',

    GET_EMPTY_ROOM:'GET_EMPTY_ROOM',
    GET_EMPTY_ROOM_FAILED:'GET_EMPTY_ROOM_FAILED',

    GET_NOT_EMPTY_ROOM:'GET_NOT_EMPTY_ROOM',
    GET_NOT_EMPTY_ROOM_FAILED:'GET_NOT_EMPTY_ROOM_FAILED',

    GET_PERSON_IN_ROOM:'GET_PERSON_IN_ROOM',
    GET_PERSON_IN_ROOM_FAILED:'GET_PERSON_IN_ROOM_FAILED',

    GET_SERVICE_IN_ROOM:'GET_SERVICE_IN_ROOM',
    GET_SERVICE_IN_ROOM_FAILED:'GET_SERVICE_IN_ROOM_FAILED',

    POST_ROOM:'POST_ROOM',
    POST_ROOM_FAILED:'POST_ROOM_FAILED',

    UN_POST_ROOM:'UN_POST_ROOM',
    UN_POST_ROOM_FAILED:'UN_POST_ROOM_FAILED',
  }
};
