export const NAME_EPICS = {
    EPIC_DICHVU_SCREEN: {
        EPIC_DICHVU_SCREEN:'EPIC_DICHVU_SCREEN',
        EPIC_GET_DICHVU:'EPIC_GET_DICHVU',
        EPIC_GET_DICHVU_FAILED:'EPIC_GET_DICHVU_FAILED',

        EPIC_EDIT_DICHVU:'EPIC_EDIT_DICHVU',
        EPIC_EDIT_DICHVU_FAILED:'EPIC_EDIT_DICHVU_FAILED',

        EPIC_CREATE_DICHVU:'EPIC_CREATE_DICHVU',
        EPIC_CREATE_DICHVU_FAILED:'EPIC_CREATE_DICHVU_FAILED',

        EPIC_DELETE_DICHVU:'EPIC_DELETE_DICHVU',
        EPIC_DELETE_DICHVU_FAILED:'EPIC_DELETE_DICHVU_FAILED',
        
    },
}