export const NAME_ACTIONS = {
  HOUSE_SCREEN: {
    HOUSE_SCREEN: 'HOUSE_SCREEN',
    GET_HOUSE: 'GET_HOUSE',
    GET_HOUSE_FAILED: 'GET_HOUSE_FAILED',

    CREATE_HOUSE:'CREATE_HOUSE',
    CREATE_HOUSE_FAILED:'CREATE_HOUSE_FAILED',
    
    EDIT_HOUSE:'EDIT_HOUSE',
    EDIT_HOUSE_FAILED:'EDIT_HOUSE_FAILED',

    DELETE_HOUSE:'DELETE_HOUSE',
    DELETE_HOUSE_FAILED:'DELETE_HOUSE_FAILED',
  }
};
